modLoader="javafml"
loaderVersion="[33,)"
license="LGPLv3"
issueTrackerURL="https://github.com/CorgiTaco/Better-Weather/issues"
[[mods]]
modId="betterweather"
version="1.2.3"
displayName="Better Weather"
displayURL="null"
logoFile="logo_text.png"
credits=""
authors="Corgi Taco"
description='''
A mod that adds more weather events! Some audio from: https://freesfx.co.uk/
'''
[[dependencies.betterweather]]
    modId="forge"
    mandatory=true
    versionRange="[33.0.0,)"
    ordering="NONE"
    side="BOTH"
