modLoader="javafml"
loaderVersion="[32,)"
#license="LGPLv3"
issueTrackerURL="https://github.com/CorgiTaco/Better-Weather/issues"
[[mods]]
modId="betterweather"
version="0.1.0"
displayName="Better Weather"
displayURL="null"
logoFile="logo_text.png"
credits=""
authors="Corgi Taco"
description='''
A mod that adds more weather events!
'''
[[dependencies.betterweather]]
    modId="forge"
    mandatory=true
    versionRange="[32.0.0,)"
    ordering="NONE"
    side="BOTH"
